feature/task-3/implementation
27ugeen/iosdt pull request #3
Opened 2022-02-18 19:32 UTC by 27ugeen

C Firebase разобрался довольно быстро - там все логично и довольно просто.

Не уверен только  - в правильных ли местах вызвал слушателей ?

Ну и самая большая проблема (скорее всего тупая и банальная), заняла у меня 4 дня. - я уже не знаю..  - не получается вынести нормально код по запросам в сеть  например во ViewModel и подключить все это...

Я не понимаю почему я не понимаю. Если все сделать в LoginViewController - все отлично работает... если выношу логику - все ломается...(((

например тут (в файле `LoginViewModel` ) не срабатывает метод пуш: 
<img width="670" alt="Screen Shot 2022-02-18 at 9 23 02 pm" src="https://user-images.githubusercontent.com/39010905/154748484-12975180-69b0-470b-8cd3-55e320ac1665.png">

почему???

тут еще б не помешал координатор, но ДЗ с прошлого модуля еще до сих пор не проверены - поэтому сюда этот код не включал..

Я понимаю принцип разделения на 
- Запросов в интернет 
- Хранения данных 
- Отображения их на UI

но запутался как это все правильно связать...(

2022-02-18 19:50 UTC, 27ugeen commented
да, и еще:

у нас есть 2 метода: авторизация и создание, но экран один - я привык (на JavaScript) - 2 таких метода- должно быть фактически два экрана, иначе не понятно что пользователь хочет сейчас сделать - создать аккаунт или войти ?

я попытался обработать этих два метода - но мне кажется получилось костыли...  - их нужно разделить..
но не вижу связи - пытаюсь зайти - ошибка 17011 (юзера нет) - создать юзера на той же View и при этом вывести allert что юзера не существует... - обычно есть ссылочка типа:  "Новый пользователь? - создать аккаунт"

2022-02-19 12:12 UTC, denisnzrk requested changes

2022-03-16 13:11 UTC, 27ugeen commented on Navigation/Profile/LogInViewController.swift
> +        handle = Auth.auth().addStateDidChangeListener { auth, user in
перенес

2022-03-16 13:12 UTC, 27ugeen commented on Navigation/Profile/LogInViewController.swift
> +    @objc func textFieldIsNotEmpty(sender: UITextField) {
вообще переделал логику по этой проверке

2022-03-16 13:13 UTC, 27ugeen commented on Navigation/Profile/LoginViewModel.swift
> +    let loginVC: UIViewController = LogInViewController()
да, абсолютно понял - перенес, не мог связать файлы модели и контроллера, в итоге получилось через замыкания.

2022-03-25 09:04 UTC, merged